### ISSUE TITLE
Open bundle for different persistence layers

### ISSUE THREAD

**Issue by ElectricMaxxx** [sonata-project/SonataClassificationBundle#262]
As the media-bundle requires the category manager for its ORM admin it would be really nice to open this bundle to phpcr and mongo too. At least the media-bundle would get the other category managers, but i think there are more this this usecase. 

I would give a hand for the phpcr stuff, but i think a BC-Break is required for that:
- explicit dependency on orm admin has to be removed
- configuration per persistence has to be introduced

What do you think?

**Comment by greg0ire** [comment]
> explicit dependency on orm admin has to be removed

related : https://github.com/sonata-project/SonataAdminBundle/issues/2118

but no, it does not have to be removed, several persistence packages can be installed together, that's not an issue.

**Comment by ElectricMaxxx** [comment]
Oh that is  a nice thing, never seen it before.
What about the configuration?

Just adding a `db_driver` key and use other defaults then?

**Comment by greg0ire** [comment]
Something like that would do I guess, if that's what you're thinking.
```yaml
sonata_classification:
   db_driver: # validate that this only has one child, which can be one of a list of supported values
       phpcr:
           specific_conf_1: value_1
```
