### ISSUE TITLE
Unable to find edit route in tree view when edit route is removed in admin class

### ISSUE THREAD

**Issue by codebach** [sonata-project/SonataClassificationBundle#308]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.18.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/cache-bundle              2.3.1  This bundle provides caching services
sonata-project/classification-bundle     3.3.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.2.1  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.1.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.0.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0  Symfony SonataNotificationBundle
sonata-project/seo-bundle                2.1.0  Symfony SonataSeoBundle
sonata-project/timeline-bundle           3.1.0  Integrates SpyTimelineBundle into Sonata
sonata-project/user-bundle               3.2.3  Symfony SonataUserBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.20 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v2.8.20 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.14-2+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14-2+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

## Subject

I have overwritten CategoryAdmin class in ApplicationSonataClasificationBundle and removed edit route. In the list view clicking on items now routes to show view. But on tree view I get an exception says edit route not found. This happens because in `Resources/views/CategoryAdmin/tree.html.twig` it always generates the edit url.

```twig
<a class="sonata-tree__item__edit" href="{{ admin.generateObjectUrl('edit', element) }}">{{ element.name }}</a>
```

## Steps to reproduce

Overwrite CategoryAdmin
```php
<?php

namespace Application\Sonata\ClassificationBundle\Admin;

use Sonata\AdminBundle\Route\RouteCollection;
use Sonata\ClassificationBundle\Admin\CategoryAdmin as SonataCategoryAdmin;

class CategoryAdmin extends SonataCategoryAdmin
{
    /**
     * {@inheritdoc}
     */
    public function configureRoutes(RouteCollection $routes)
    {
        parent::configureRoutes($routes);

        $routes->remove('delete');
        $routes->remove('create');
        $routes->remove('edit');
    }
}
```
overwrite admin service in `Application/Sonata/ClassificationBundle/Resources/config/services.yml`
```yaml
services:
     sonata.classification.admin.category:
         class: Application\Sonata\ClassificationBundle\Admin\CategoryAdmin
         arguments: [~, Application\Sonata\ClassificationBundle\Entity\Category, SonataClassificationBundle:CategoryAdmin, '@sonata.classification.manager.context']
         calls:
             - [ setTemplate, [tree, "SonataClassificationBundle:CategoryAdmin:tree.html.twig"]]
             - [ setTemplate, [list, "SonataClassificationBundle:CategoryAdmin:list.html.twig"]]
         tags:
             - { name: sonata.admin, manager_type: orm, group: admin, label: Kategorien }
```
Visit category list view (it works)
Visit category tree view (throws exception)

## Expected results
on tree view and list view clicking on items should route to show view.
## Actual results
on tree view throws exception.

### Suggestion
In `Resources/views/CategoryAdmin/tree.html.twig` we can change:

From this:
```twig
<a class="sonata-tree__item__edit" href="{{ admin.generateObjectUrl('edit', element) }}">{{ element.name }}</a>
```

To this:
```twig
{% if admin.hasRoute('edit') %}
    <a class="sonata-tree__item__edit" href="{{ admin.generateObjectUrl('edit', element) }}">{{ element.name }}</a>
{% elseif admin.hasRoute('show') %}
    <a class="sonata-tree__item__edit" href="{{ admin.generateObjectUrl('show', element) }}">{{ element.name }}</a>
{% else %}
    {{ element.name }}
{% endif %}
```
