### ISSUE TITLE
Cannot save new Category

### ISSUE THREAD

**Issue by deafboy2k9** [sonata-project/SonataClassificationBundle#89]
When attempting to save a new category via SonataAdmin I get the following error:

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'enabled' cannot be null

Currently the form to create a new category does not include the enabled field. Likewise, when digging into the BaseCategory.orm.xml file, PHPStorm picks up an error that says:

"Attribute 'default' is not allowed to appear in element field"

My current composer looks as follows:

```
   "sonata-project/admin-bundle": "dev-master",
   "sonata-project/doctrine-orm-admin-bundle": "dev-master",
    "sonata-project/core-bundle": "dev-master",
    "sonata-project/easy-extends-bundle": "dev-master",
    "sonata-project/user-bundle": "dev-master",
    "sonata-project/datagrid-bundle": "dev-master",
    "sonata-project/formatter-bundle": "~2.3",
    "sonata-project/intl-bundle": "~2.2",
    "sonata-project/cache-bundle": "~2.2",
    "sonata-project/seo-bundle": "~1.1",
    "sonata-project/classification-bundle": "~2.2",
    "sonata-project/media-bundle": "~2.3",
    "sonata-project/news-bundle": "~2.3",
```

**Comment by sergiostrampelli** [comment]
This is a bug of 2.2 but the dev is unstable ...

What do you think about a maintenance 2.2.1 ?

**Comment by webdevilopers** [comment]
:+1:

**Comment by bartoszmalec** [comment]
You can fix it.

Add new service and extension of category class:

Service:
```
sonata.classification.admin.category.extension:
    class: Application\Sonata\ClassificationBundle\Admin\Extensions\CategoryAdminExtension
    tags:
       - { name: sonata.admin.extension, target: sonata.classification.admin.category }
```

Class (Extension of Admin):
```
namespace Application\Sonata\ClassificationBundle\Admin\Extensions;

use Sonata\AdminBundle\Admin\AdminExtension;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Admin\AdminInterface;

class CategoryAdminExtension extends AdminExtension
{
    /**
     * {@inheritdoc}
     */
    public function prePersist(AdminInterface $admin, $object)
    {
        $object->setEnabled(false);
    }
}
```
